### ISSUE TITLE
Unhandled exception.

### ISSUE THREAD

**Issue by jerry110** [smccloud/pfSense-to-OPNSense-Config-File-Converter#26]
![Screenshot 2023-11-16 221818](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/6697716/1354ea70-d56d-4b3c-86cc-43f788371498)
Unhandled exception. System.InvalidOperationException: There is an error in XML document (5, 3).
---> System.FormatException: Input string was not in a correct format.

FVM Tae Samba) ON See ate The ocak G eS hhe- ta ee he. he 1G l 7 ot

at System.Double.Parse(String s, NumberStyles style, IFormatProvider provider)

EVN E38. PO DO LEG LL ELE h eee 8]

at Microsoft .Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPfsense.Read1_NullableOfDouble(Boolean checkTy
pe)

at Microsoft .Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPfsense.Readd8_Pfsense(Boolean isNullable, Boo
lean checkType)

at Microsoft .Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPfsense.Readd9_pfsense()

--- End of inner exception stack trace ---

at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEv
Chae eB

at System.Xml.Serialization.XmlSerializer.Deserialize(Stream strean)

at Program.<Main>$(String[] args)

**Comment by dannygee87** [comment]
Same here

![grafik](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/12453436/df28aa24-315e-4669-b69e-979ce8b587e4)

**Comment by smccloud** [comment]
Please send your config files to converter@smccloud.com so I can see what is wrong with them.

**Comment by smccloud** [comment]
I broke something in 0.3.0, please use 0.2.4 for now.

**Comment by jerry110** [comment]
OPS lol ok thank you!

**Comment by jerry110** [comment]
windows-x64.-.0.2.4 Same Deal no joy
![Screenshot 2023-11-17 162448](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/6697716/8d022d87-173f-430c-8c98-79745ddc5a74)

**Comment by jerry110** [comment]
0.2.4 Same deal no joy........
![Screenshot 2023-11-17 162812](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/6697716/462f79b5-4cbc-4927-90b1-99895067af6f)

**Comment by smccloud** [comment]
What is on line 130 of your pfSense XML config file?

**Comment by jerry110** [comment]
![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/6697716/dd7f200e-277c-4014-973f-6fc3290044e6)

**Comment by jerry110** [comment]
![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/6697716/27c50019-f38d-4e44-91c5-774e85faf542)

**Comment by smccloud** [comment]
I'll hopefully be able to look at it Sunday.  Coming down with something and tomorrow is our first Thanksgiving celebration of the year.

**Comment by jerry110** [comment]
Cool ...feel better ....

**Comment by jerry110** [comment]
No joy on 0.2.5
![image](https://github.com/smccloud/pfSense-to-OPNSense-Config-File-Converter/assets/6697716/b47c372f-fb53-453f-99be-cb20d1fc9c4d)

**Comment by jerry110** [comment]
This is on pfsense 23.09
